# Generated by Django 5.2.17 on 2026-09-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
